# web server
server:
  port: 8080
  servlet:
    context-path: /myapp

# spring
spring:
  application:
    name: hello-web
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: h2
    schema: classpath:schema.sql #可以自定义文件名
    data: classpath:data.sql #可以自定义文件名
  # jpa
  jpa:
    hibernate:
      ddl-auto: update #只有是update模式,data.sql的脚本才会被执行
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  # h2
  h2:
    console:
      enabled: true
      path: /h2-console
  resources:
    # static-locations指向容纳静态文件的文件夹
    static-locations: classpath:/static-web-resources/
  mvc:
    # static-path-pattern标识静态文件的前缀.
    # 举例: http://localhost:9080/myapp/static/web/pdf/viewer.html中, uri(/myapp/static/web/pdf/viewer.html)去除context-path(/myapp),去除static-path-pattern(/static),剩余的(web/pdf/viewer.html)去static-locations目录下找同路径文件
    static-path-pattern: /static/**


# logging
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

